In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
import cv2
import glob
import os
from mpl_toolkits.mplot3d import Axes3D
from sklearn.linear_model import LinearRegression
from sklearn.cluster import KMeans
from sklearn.neighbors import BallTree
import pickle
from tqdm import tqdm
import das.imu as DI
from das.api import platform, interpolators
from leddar_utils import linalg
import extrinsic_ouster64_camera as E
import averagingSO3 as so

In [2]:
%matplotlib

Using matplotlib backend: Qt5Agg


In [3]:
#Define the Checkerboard
checkerboard = E.Checkerboard(pattern=(4,3), square_length=0.145)
checkerboard.points

array([[0.   , 0.   , 0.   ],
       [0.145, 0.   , 0.   ],
       [0.29 , 0.   , 0.   ],
       [0.435, 0.   , 0.   ],
       [0.   , 0.145, 0.   ],
       [0.145, 0.145, 0.   ],
       [0.29 , 0.145, 0.   ],
       [0.435, 0.145, 0.   ],
       [0.   , 0.29 , 0.   ],
       [0.145, 0.29 , 0.   ],
       [0.29 , 0.29 , 0.   ],
       [0.435, 0.29 , 0.   ]], dtype=float32)

In [4]:
#Load datasets, platforms, and frames range:
__datasets=[
    '/nas/pixset/exportedDataset/20200325_145233_rec_dataset_calib_jeanne01_exported/',
    '/nas/pixset/exportedDataset/20200325_151131_rec_dataset_calib_paul01_exported/',
    '/nas/pixset/exportedDataset/20200407_112921_rec_dataset_calib_jeanne02_gd_carreaux_exported/',
    '/nas/pixset/exportedDataset/20200407_124505_rec_dataset_calib_paul02_gd_carreaux_exported/',
    '/nas/pixset/exportedDataset/20200502_172647_rec_dataset_pierre01_grands_carreaux_exported/',
    '/nas/pixset/exportedDataset/20200502_172126_rec_dataset_jeanne03_grands_carreaux_exported/'
] 

pfs = [platform.Platform(omega) for omega in __datasets]

source = 'ouster64_bfc_xyzit'
destination = 'flir_bfc_img'

  0%|          | 0/6 [00:00<?, ?it/s]/home/olivier/workspace/das/das/api/sensors.py:687: UserWarning: Unable to read completely data from cfg file
  warnings.warn("Unable to read completely data from cfg file")
 17%|█▋        | 1/6 [00:00<00:00,  6.21it/s]/home/olivier/workspace/das/das/api/filesource.py:261: UserWarning: Timestamps are not strictly increasing for datasource file /nas/pixset/exportedDataset/20200325_145233_rec_dataset_calib_jeanne01_exported/flir_bfr_img.zip
  warnings.warn('Timestamps are not strictly increasing for datasource file {}'.format(self.path))
 33%|███▎      | 2/6 [00:00<00:00,  6.68it/s]

Pixell Log: The cache is set to use calibration angles.


 33%|███▎      | 2/6 [00:00<00:00,  6.23it/s]

Pixell Log: The cache is set to use calibration angles.


 50%|█████     | 3/6 [00:00<00:00,  6.01it/s]/home/olivier/workspace/das/das/api/filesource.py:261: UserWarning: Timestamps are not strictly increasing for datasource file /nas/pixset/exportedDataset/20200325_151131_rec_dataset_calib_paul01_exported/flir_bfl_img.zip
  warnings.warn('Timestamps are not strictly increasing for datasource file {}'.format(self.path))
 33%|███▎      | 2/6 [00:00<00:00,  5.86it/s]

Pixell Log: The cache is set to use calibration angles.


/home/olivier/workspace/das/das/api/filesource.py:261: UserWarning: Timestamps are not strictly increasing for datasource file /nas/pixset/exportedDataset/20200407_112921_rec_dataset_calib_jeanne02_gd_carreaux_exported/flir_bfc_img.zip
  warnings.warn('Timestamps are not strictly increasing for datasource file {}'.format(self.path))
 17%|█▋        | 1/6 [00:00<00:00,  5.51it/s]/home/olivier/workspace/das/das/api/filesource.py:261: UserWarning: Timestamps are not strictly increasing for datasource file /nas/pixset/exportedDataset/20200407_124505_rec_dataset_calib_paul02_gd_carreaux_exported/flir_bfr_img.zip
  warnings.warn('Timestamps are not strictly increasing for datasource file {}'.format(self.path))
 33%|███▎      | 2/6 [00:00<00:00,  6.03it/s]

Pixell Log: The cache is set to use calibration angles.


 50%|█████     | 3/6 [00:00<00:00,  5.65it/s]/home/olivier/workspace/das/das/api/filesource.py:261: UserWarning: Timestamps are not strictly increasing for datasource file /nas/pixset/exportedDataset/20200407_124505_rec_dataset_calib_paul02_gd_carreaux_exported/flir_bfl_img.zip
  warnings.warn('Timestamps are not strictly increasing for datasource file {}'.format(self.path))
 33%|███▎      | 2/6 [00:00<00:00,  6.82it/s]

Pixell Log: The cache is set to use calibration angles.
Pixell Log: time base delays are converted to lcas referential.


 33%|███▎      | 2/6 [00:00<00:00,  6.04it/s]

Pixell Log: The cache is set to use calibration angles.
Pixell Log: time base delays are converted to lcas referential.


100%|██████████| 6/6 [00:00<00:00,  8.36it/s]


In [5]:
#frames of interest from flir_bfc in same order as platform:
__frames_bfc = [
    np.concatenate((np.arange(2,11),
                        np.arange(37,131),
                        np.arange(175,187),
                        np.arange(241,426))),
    np.concatenate((np.arange(0,40),
                        np.arange(75,80),
                        np.arange(111,166),
                        np.arange(250,310),
                        np.arange(353,439))),
    np.arange(1,192),
    np.concatenate((np.arange(0,264),
                        np.arange(397,404))),
    np.concatenate((np.arange(15,24),
                           np.arange(33,40),
                           np.arange(53,69),
                           np.arange(75,92),
                           np.arange(109,120),
                           np.arange(129,140))),
    np.concatenate((np.arange(3,9),
                           np.arange(88,95),
                           np.arange(124,133),
                           np.arange(150,165),
                           np.arange(193,250),
                           np.arange(254,258),
                           np.arange(292,314)))
]

In [6]:
#Parameters of initial guess:
#The homogenous transformation from flir_camera to camera can be obtained from dasview, or by
# solving a single frame with SVD.

#Camera must have intrinsic calib first:
mtx, dist = E.load_intrinsic_camera(__datasets[5]+'intrinsics/flir_bfc_calib-results.pkl')

with open(__datasets[0]+'extrinsics/ouster64_tfc-flir_bfc.pkl', 'rb') as g:
    tf_from_ouster_to_flir_bfc = pickle.load(g)

tf_from_flir_bfc_to_ouster = linalg.tf_inv(tf_from_ouster_to_flir_bfc)
r, t = tf_from_flir_bfc_to_ouster[:3,:3], tf_from_flir_bfc_to_ouster[:3,3:]

In [7]:
mtx, dist, r, t

(array([[820.24753975,   0.        , 734.30704743],
        [  0.        , 820.78873052, 552.62262377],
        [  0.        ,   0.        ,   1.        ]]),
 array([[-0.22649187,  0.10065042, -0.00026163, -0.00022689, -0.02206318]]),
 array([[ 6.06826773e-03, -2.02354674e-05,  9.99981588e-01],
        [-9.99947570e-01, -8.24850946e-03,  6.06789438e-03],
        [ 8.24823480e-03, -9.99965980e-01, -7.02885703e-05]]),
 array([[ 0.13941018],
        [-0.00108739],
        [-0.10272664]]))

In [8]:
DI.print_transf_result(tf_from_flir_bfc_to_ouster)

translations :[ 0.13941018 -0.00108739 -0.10272664], norm:0.17317373549655454
Ax Angle vector:[-0.58127064  0.57300802 -0.57774238], angle (deg):120.07447490928172
Euler Angle (deg):[-90.00402738  -0.4725944  -89.65229991]


In [9]:
prior_bfc = E.ProtoCameraToLidar(checkerboard, mtx, dist, r,t,'c', epsilons=(1.5,1.25,1.25))

In [21]:
#Init params:
corners_cam_uv = []
corners_ous = []
corners_cam = []


In [22]:
corners_mask = []
corners_mask_ = [
    0,1,1,0,
    0,1,1,0,
    0,1,1,0
]
#corners_mask_ = [
#    0,0,0,0,
#    0,1,1,0,
#    0,0,0,0
#]

In [23]:
#iterate over all frames:
frames =  __frames_bfc[5]#[15:17]
pf = pfs[5]
SHOW_ = False
for mu in tqdm(frames):
    sample_flir = pf[destination][mu]
    sample_lidar = pf[source].get_at_timestamp(sample_flir.timestamp,
                                             interpolator=interpolators.nearest_interpolator)
    
    img = np.copy(sample_flir.raw)
    X = sample_lidar.point_cloud()
    A = sample_lidar.amplitudes
    
    ret_cam, corners_cam_uv_ = E.get_camera_corners(img, 
                                                    checkerboard, 
                                                    SHOW_)
   
    if ret_cam:
        try:
            corners_cam_uv_ = corners_cam_uv_[::-1,:,:]
            ret_ous, corners_ous_, corners_cam_ = E.get_lidar_corners(X, A, prior_bfc, 
                                                            corners_cam_uv_, 
                                                            SHOW_, 
                                                            tolerance_eps=0.020, 
                                                            tolerance_nedges=7)
            if ret_ous:
                corners_cam_uv.append(corners_cam_uv_)
                corners_cam.append(corners_cam_)
                corners_ous.append(corners_ous_)
                corners_mask.append(corners_mask_)
        except:
            pass


  1%|          | 1/120 [00:00<00:24,  4.88it/s]

Log: 3D points for ouster64_bfc are corrected with T 25.94: global offset is -0.15



  2%|▏         | 2/120 [00:00<00:23,  4.93it/s]

Log: 3D points for ouster64_bfc are corrected with T 25.94: global offset is -0.15
Log: 3D points for ouster64_bfc are corrected with T 25.94: global offset is -0.15



  3%|▎         | 4/120 [00:02<01:20,  1.45it/s]

Log: 3D points for ouster64_bfc are corrected with T 25.94: global offset is -0.15
Log: 3D points for ouster64_bfc are corrected with T 25.94: global offset is -0.15



  4%|▍         | 5/120 [00:03<01:33,  1.23it/s]

Log: 3D points for ouster64_bfc are corrected with T 25.94: global offset is -0.15



  5%|▌         | 6/120 [00:05<02:15,  1.18s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



  6%|▌         | 7/120 [00:08<02:57,  1.57s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



  7%|▋         | 8/120 [00:09<02:53,  1.55s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



  8%|▊         | 9/120 [00:10<02:27,  1.33s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



  8%|▊         | 10/120 [00:11<02:19,  1.27s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



  9%|▉         | 11/120 [00:12<02:10,  1.20s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 10%|█         | 12/120 [00:14<02:31,  1.40s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 11%|█         | 13/120 [00:15<02:18,  1.30s/it]

Log: 3D points for ouster64_bfc are corrected with T 25.81: global offset is -0.15



 12%|█▎        | 15/120 [00:18<02:31,  1.44s/it]

Log: 3D points for ouster64_bfc are corrected with T 25.81: global offset is -0.15
Log: 3D points for ouster64_bfc are corrected with T 25.87: global offset is -0.15



 13%|█▎        | 16/120 [00:18<01:51,  1.07s/it]

Log: 3D points for ouster64_bfc are corrected with T 25.87: global offset is -0.15



 14%|█▍        | 17/120 [00:19<01:24,  1.22it/s]

Log: 3D points for ouster64_bfc are corrected with T 25.81: global offset is -0.15



 16%|█▌        | 19/120 [00:19<00:51,  1.97it/s]

Log: 3D points for ouster64_bfc are corrected with T 25.81: global offset is -0.15
Log: 3D points for ouster64_bfc are corrected with T 25.81: global offset is -0.15



 17%|█▋        | 20/120 [00:19<00:42,  2.35it/s]

Log: 3D points for ouster64_bfc are corrected with T 25.81: global offset is -0.15



 18%|█▊        | 21/120 [00:21<01:25,  1.15it/s]

Log: 3D points for ouster64_bfc are corrected with T 25.81: global offset is -0.15



 19%|█▉        | 23/120 [00:24<01:46,  1.10s/it]

Log: 3D points for ouster64_bfc are corrected with T 25.81: global offset is -0.15



 20%|██        | 24/120 [00:25<01:40,  1.05s/it]

Log: 3D points for ouster64_bfc are corrected with T 25.81: global offset is -0.15



 21%|██        | 25/120 [00:25<01:30,  1.05it/s]

Log: 3D points for ouster64_bfc are corrected with T 25.81: global offset is -0.15



 22%|██▏       | 26/120 [00:26<01:31,  1.02it/s]

Log: 3D points for ouster64_bfc are corrected with T 25.81: global offset is -0.15
Log: 3D points for ouster64_bfc are corrected with T 25.81: global offset is -0.15



 22%|██▎       | 27/120 [00:29<02:04,  1.34s/it]

Log: 3D points for ouster64_bfc are corrected with T 25.81: global offset is -0.15



 24%|██▍       | 29/120 [00:32<02:19,  1.54s/it]

Log: 3D points for ouster64_bfc are corrected with T 25.81: global offset is -0.15



 25%|██▌       | 30/120 [00:33<02:00,  1.34s/it]

Log: 3D points for ouster64_bfc are corrected with T 25.81: global offset is -0.15



 26%|██▌       | 31/120 [00:34<01:48,  1.22s/it]

Log: 3D points for ouster64_bfc are corrected with T 25.81: global offset is -0.15
Log: 3D points for ouster64_bfc are corrected with T 25.81: global offset is -0.15



 28%|██▊       | 33/120 [00:36<01:41,  1.16s/it]

Log: 3D points for ouster64_bfc are corrected with T 25.81: global offset is -0.15



 28%|██▊       | 34/120 [00:37<01:35,  1.12s/it]

Log: 3D points for ouster64_bfc are corrected with T 25.81: global offset is -0.15



 29%|██▉       | 35/120 [00:38<01:31,  1.08s/it]

Log: 3D points for ouster64_bfc are corrected with T 25.81: global offset is -0.15



 30%|███       | 36/120 [00:39<01:23,  1.00it/s]

Log: 3D points for ouster64_bfc are corrected with T 25.81: global offset is -0.15
Log: 3D points for ouster64_bfc are corrected with T 25.87: global offset is -0.15



 32%|███▏      | 38/120 [00:42<01:41,  1.23s/it]

Log: 3D points for ouster64_bfc are corrected with T 25.94: global offset is -0.15



 32%|███▎      | 39/120 [00:44<01:52,  1.38s/it]

Log: 3D points for ouster64_bfc are corrected with T 25.94: global offset is -0.15
Log: 3D points for ouster64_bfc are corrected with T 25.94: global offset is -0.15



 33%|███▎      | 40/120 [00:46<02:06,  1.59s/it]

Log: 3D points for ouster64_bfc are corrected with T 25.94: global offset is -0.15



 35%|███▌      | 42/120 [00:49<01:56,  1.49s/it]

Log: 3D points for ouster64_bfc are corrected with T 25.94: global offset is -0.15



 36%|███▌      | 43/120 [00:50<01:44,  1.36s/it]

Log: 3D points for ouster64_bfc are corrected with T 25.94: global offset is -0.15



 37%|███▋      | 44/120 [00:51<01:36,  1.28s/it]

Log: 3D points for ouster64_bfc are corrected with T 25.94: global offset is -0.15
Log: 3D points for ouster64_bfc are corrected with T 25.94: global offset is -0.15



 38%|███▊      | 45/120 [00:52<01:32,  1.24s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 39%|███▉      | 47/120 [00:55<01:38,  1.35s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15
Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 41%|████      | 49/120 [00:58<01:33,  1.31s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 42%|████▏     | 50/120 [00:59<01:24,  1.21s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15
Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 42%|████▎     | 51/120 [01:01<01:39,  1.44s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 44%|████▍     | 53/120 [01:04<01:34,  1.41s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 45%|████▌     | 54/120 [01:06<01:47,  1.63s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 46%|████▌     | 55/120 [01:08<01:45,  1.62s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 47%|████▋     | 56/120 [01:09<01:33,  1.46s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 48%|████▊     | 57/120 [01:10<01:33,  1.49s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15
Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 49%|████▉     | 59/120 [01:14<01:42,  1.67s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15
Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 51%|█████     | 61/120 [01:17<01:21,  1.39s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 52%|█████▏    | 62/120 [01:18<01:13,  1.27s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 52%|█████▎    | 63/120 [01:19<01:08,  1.20s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 53%|█████▎    | 64/120 [01:19<01:00,  1.08s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 54%|█████▍    | 65/120 [01:20<00:55,  1.01s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15
Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 56%|█████▌    | 67/120 [01:23<01:10,  1.33s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 57%|█████▋    | 68/120 [01:25<01:20,  1.54s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15
Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 58%|█████▊    | 70/120 [01:28<01:13,  1.48s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15
Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 60%|██████    | 72/120 [01:31<01:01,  1.29s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 61%|██████    | 73/120 [01:32<00:59,  1.26s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 62%|██████▏   | 74/120 [01:34<01:03,  1.37s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15
Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 62%|██████▎   | 75/120 [01:35<00:57,  1.27s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 63%|██████▎   | 76/120 [01:36<01:03,  1.45s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 64%|██████▍   | 77/120 [01:38<01:08,  1.60s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 65%|██████▌   | 78/120 [01:40<01:01,  1.46s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 66%|██████▌   | 79/120 [01:41<00:55,  1.35s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 67%|██████▋   | 80/120 [01:42<00:49,  1.24s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 68%|██████▊   | 81/120 [01:43<00:56,  1.44s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 68%|██████▊   | 82/120 [01:46<01:04,  1.71s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 70%|███████   | 84/120 [01:49<00:56,  1.57s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15
Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 71%|███████   | 85/120 [01:50<00:50,  1.45s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 72%|███████▎  | 87/120 [01:53<00:45,  1.38s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 73%|███████▎  | 88/120 [01:54<00:40,  1.28s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 74%|███████▍  | 89/120 [01:54<00:34,  1.13s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15
Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 76%|███████▌  | 91/120 [01:57<00:31,  1.10s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15



 77%|███████▋  | 92/120 [01:58<00:32,  1.15s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.0: global offset is -0.15


Log: 3D points for ouster64_bfc are corrected with T 26.06: global offset is -0.15



 78%|███████▊  | 93/120 [01:59<00:29,  1.10s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.06: global offset is -0.15



 78%|███████▊  | 94/120 [02:01<00:34,  1.31s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.06: global offset is -0.15



 79%|███████▉  | 95/120 [02:02<00:30,  1.22s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.06: global offset is -0.15



 80%|████████  | 96/120 [02:05<00:45,  1.90s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.06: global offset is -0.15



 81%|████████  | 97/120 [02:06<00:36,  1.58s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.06: global offset is -0.15



 82%|████████▏ | 98/120 [02:07<00:31,  1.42s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.12: global offset is -0.15



 82%|████████▎ | 99/120 [02:09<00:31,  1.49s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.12: global offset is -0.15



 83%|████████▎ | 100/120 [02:10<00:27,  1.38s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.12: global offset is -0.15



 84%|████████▍ | 101/120 [02:11<00:25,  1.34s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.12: global offset is -0.15



 85%|████████▌ | 102/120 [02:13<00:26,  1.49s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.12: global offset is -0.15



 86%|████████▌ | 103/120 [02:14<00:22,  1.32s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.12: global offset is -0.15



 87%|████████▋ | 104/120 [02:15<00:20,  1.25s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.12: global offset is -0.15



 88%|████████▊ | 105/120 [02:17<00:22,  1.49s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.12: global offset is -0.15



 88%|████████▊ | 106/120 [02:19<00:22,  1.64s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.12: global offset is -0.15



 89%|████████▉ | 107/120 [02:20<00:18,  1.39s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.12: global offset is -0.15



 90%|█████████ | 108/120 [02:21<00:15,  1.28s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.19: global offset is -0.15



 91%|█████████ | 109/120 [02:22<00:13,  1.19s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.19: global offset is -0.15



 92%|█████████▏| 110/120 [02:24<00:14,  1.43s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.19: global offset is -0.15



 92%|█████████▎| 111/120 [02:26<00:14,  1.62s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.19: global offset is -0.15



 93%|█████████▎| 112/120 [02:28<00:13,  1.70s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.19: global offset is -0.15



 94%|█████████▍| 113/120 [02:30<00:12,  1.84s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.19: global offset is -0.15



 96%|█████████▌| 115/120 [02:32<00:07,  1.48s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.19: global offset is -0.15
Log: 3D points for ouster64_bfc are corrected with T 26.19: global offset is -0.15



 97%|█████████▋| 116/120 [02:34<00:06,  1.66s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.19: global offset is -0.15



 98%|█████████▊| 118/120 [02:38<00:03,  1.75s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.19: global offset is -0.15
Log: 3D points for ouster64_bfc are corrected with T 26.19: global offset is -0.15



 99%|█████████▉| 119/120 [02:39<00:01,  1.49s/it]

Log: 3D points for ouster64_bfc are corrected with T 26.19: global offset is -0.15



100%|██████████| 120/120 [02:40<00:00,  1.34s/it]


In [ ]:
#Once all frames have been selected, do the following:

In [24]:
stack_corners_cam_uv = np.vstack(corners_cam_uv).squeeze(1)
stack_corners_cam = np.vstack(corners_cam)
stack_corners_ous = np.vstack(corners_ous)
stack_corners_mask = np.hstack(corners_mask).astype(bool)

In [25]:
stack_corners_cam_uv.shape, stack_corners_cam.shape, stack_corners_ous.shape

((1152, 2), (1152, 3), (1152, 3))

In [26]:
stack_corners_cam_uv = stack_corners_cam_uv[stack_corners_mask]
stack_corners_ous = stack_corners_ous[stack_corners_mask]
stack_corners_cam = stack_corners_cam[stack_corners_mask]

In [27]:
#display the space of points
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(stack_corners_cam[:,0], stack_corners_cam[:,1], stack_corners_cam[:,2], s=50, color='orange', marker='d', label='camera points')
ax.scatter(stack_corners_ous[:,0], stack_corners_ous[:,1], stack_corners_ous[:,2], s=50,color='green' , marker='o', label='ouster points')
plt.legend()
plt.show()

In [28]:
#using svd to obtain affine transformation from ouster to camera:
Rot_,Trans_=E.euclidean_transform_3D(stack_corners_ous, stack_corners_cam)

In [29]:
Rot_, Trans_

(array([[-7.52183604e-04, -9.99985841e-01,  5.26798341e-03],
        [ 1.58678639e-03, -5.26917181e-03, -9.99984859e-01],
        [ 9.99998458e-01, -7.43813051e-04,  1.59072731e-03]]),
 array([ 0.0168517 , -0.10350207, -0.15225468]))

In [30]:
#replace svd by pnp ransac
f, r_, t_, a = cv2.solvePnPRansac(stack_corners_ous, stack_corners_cam_uv, mtx, dist, 
                                          iterationsCount=1500, reprojectionError=1.5)
r_, _ = cv2.Rodrigues(r_)
f,len(a)

(True, 160)

In [31]:
r_, t_

(array([[ 1.43941155e-03, -9.99981705e-01,  5.87523992e-03],
        [ 9.20798323e-06, -5.87523275e-03, -9.99982741e-01],
        [ 9.99998964e-01,  1.43944080e-03,  7.50936889e-07]]),
 array([[ 0.00800188],
        [-0.09493692],
        [-0.12493336]]))

In [32]:
# Transformation Matrix.
M = np.eye(4)
M[:3,:3] = r_
M[:3,3:]= t_

In [33]:
#Save result:
pickle.dump(M, open("ouster64_bfc-flir_bfc.pkl", "wb"))

In [34]:
DI.print_transf_result(M)

translations :[ 0.00800188 -0.09493692 -0.12493336], norm:0.15711585627337732
Ax Angle vector:[ 0.57902991 -0.57480989  0.57820234], angle (deg):120.14681971058945
Euler Angle (deg):[ 89.97010957 -89.91752608   0.36651879]


In [36]:
#Evaluation of error:
ous_to_cam = (Rot_.dot(stack_corners_ous.T) + Trans_[:,None]).T
err_ = E.lj_error(ous_to_cam,stack_corners_cam)
plt.figure()
plt.hist(err_, bins=100)
plt.show()